### ISSUE TITLE
Getting Error:requests.exceptions.SSLError: HTTPSConnectionPool(host='www.nseindia.com', port=443): Max retries exceeded with url

### ISSUE THREAD

**Issue by Jainu-s** [jugaad-py/jugaad-data#4]
It worked fine yesterday but today it is showing error. This is the only python library that working fine with historical data without much code. Please sort out this issue thanks.

**Comment by sevakram** [comment]
Hi @Jainu-s 
Can you please provide more information

please share the code snippet and error traceback

My observation is that new NSE website is not reliable, data url is down many times

**Comment by Jainu-s** [comment]
Hi Sir, now it's working fine sir. There is no quote end error. Thanks, sir. By the way, if possible please provide a realtime data feed. also, I would like to buy you a coffee if you share your Patreon or any other link.

**Comment by sevakram** [comment]
Thank you so much for your kind gesture 👍  That is really encouraging..
I haven't opened patreon account yet :)

**Comment by Jainu-s** [comment]
Do you have any about the Heroku(cloud) platform?  when I installed and run your library I'm getting the below error? can you sort out whats the issue?

2020-10-01T16:25:00.360373+00:00 app[worker.1]: started.......
2020-10-01T16:25:02.624185+00:00 app[worker.1]: Traceback (most recent call last):
2020-10-01T16:25:02.624212+00:00 app[worker.1]: File "script.py", line 424, in <module>
2020-10-01T16:25:02.624472+00:00 app[worker.1]: schedule.run_pending()
2020-10-01T16:25:02.624474+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/schedule/__init__.py", line 563, in run_pending
2020-10-01T16:25:02.624754+00:00 app[worker.1]: default_scheduler.run_pending()
2020-10-01T16:25:02.624756+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/schedule/__init__.py", line 94, in run_pending
2020-10-01T16:25:02.624895+00:00 app[worker.1]: self._run_job(job)
2020-10-01T16:25:02.624897+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/schedule/__init__.py", line 147, in _run_job
2020-10-01T16:25:02.625105+00:00 app[worker.1]: ret = job.run()
2020-10-01T16:25:02.625109+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/schedule/__init__.py", line 466, in run
2020-10-01T16:25:02.625367+00:00 app[worker.1]: ret = self.job_func()
2020-10-01T16:25:02.625368+00:00 app[worker.1]: File "script.py", line 311, in nifty_500_stocks
2020-10-01T16:25:02.625554+00:00 app[worker.1]: series="EQ")
2020-10-01T16:25:02.625560+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/jugaad_data/nse/__init__.py", line 170, in stock_df
2020-10-01T16:25:02.625720+00:00 app[worker.1]: raw = stock_raw(symbol, from_date, to_date, series)
2020-10-01T16:25:02.625724+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/jugaad_data/nse/__init__.py", line 108, in stock_raw
2020-10-01T16:25:02.625869+00:00 app[worker.1]: return list(itertools.chain.from_iterable(chunks))
2020-10-01T16:25:02.625873+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
2020-10-01T16:25:02.626149+00:00 app[worker.1]: yield fs.pop().result()
2020-10-01T16:25:02.626154+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/concurrent/futures/_base.py", line 425, in result
2020-10-01T16:25:02.626372+00:00 app[worker.1]: return self.__get_result()
2020-10-01T16:25:02.626376+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
2020-10-01T16:25:02.626586+00:00 app[worker.1]: raise self._exception
2020-10-01T16:25:02.626590+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/concurrent/futures/thread.py", line 56, in run
2020-10-01T16:25:02.626724+00:00 app[worker.1]: result = self.fn(*self.args, **self.kwargs)
2020-10-01T16:25:02.626728+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/jugaad_data/util.py", line 109, in wrapper
2020-10-01T16:25:02.626871+00:00 app[worker.1]: os.makedirs(cache_dir)
2020-10-01T16:25:02.626875+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/os.py", line 220, in makedirs
2020-10-01T16:25:02.627099+00:00 app[worker.1]: mkdir(name, mode)
2020-10-01T16:25:02.627129+00:00 app[worker.1]: FileExistsError: [Errno 17] File exists: '/app/.cache/nsehistory-stock'
2020-10-01T16:25:02.778307+00:00 heroku[worker.1]: Process exited with status 1
