### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Jainu-s** [jugaad-py/jugaad-data#5]
**I'm getting the below error when I run your code on Heroku and I tried on desktop its working fine buy on the cloud it is displaying the error:**

2020-10-01T18:20:03.659025+00:00 app[worker.1]: started.......
2020-10-01T18:20:05.585950+00:00 app[worker.1]: Traceback (most recent call last):
2020-10-01T18:20:05.586335+00:00 app[worker.1]: File "script.py", line 420, in <module>
2020-10-01T18:20:05.586914+00:00 app[worker.1]: schedule.run_pending()
2020-10-01T18:20:05.586954+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/schedule/__init__.py", line 563, in run_pending
2020-10-01T18:20:05.587443+00:00 app[worker.1]: default_scheduler.run_pending()
2020-10-01T18:20:05.587478+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/schedule/__init__.py", line 94, in run_pending
2020-10-01T18:20:05.587736+00:00 app[worker.1]: self._run_job(job)
2020-10-01T18:20:05.591719+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/schedule/__init__.py", line 147, in _run_job
2020-10-01T18:20:05.592011+00:00 app[worker.1]: ret = job.run()
2020-10-01T18:20:05.592051+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/schedule/__init__.py", line 466, in run
2020-10-01T18:20:05.592485+00:00 app[worker.1]: ret = self.job_func()
2020-10-01T18:20:05.592525+00:00 app[worker.1]: File "script.py", line 307, in nifty_500_stocks
2020-10-01T18:20:05.592856+00:00 app[worker.1]: series="EQ")
2020-10-01T18:20:05.592892+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/jugaad_data/nse/__init__.py", line 170, in stock_df
2020-10-01T18:20:05.593144+00:00 app[worker.1]: raw = stock_raw(symbol, from_date, to_date, series)
2020-10-01T18:20:05.593179+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/jugaad_data/nse/__init__.py", line 108, in stock_raw
2020-10-01T18:20:05.593417+00:00 app[worker.1]: return list(itertools.chain.from_iterable(chunks))
2020-10-01T18:20:05.593527+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
2020-10-01T18:20:05.594038+00:00 app[worker.1]: yield fs.pop().result()
2020-10-01T18:20:05.594076+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/concurrent/futures/_base.py", line 425, in result
2020-10-01T18:20:05.594459+00:00 app[worker.1]: return self.__get_result()
2020-10-01T18:20:05.594500+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
2020-10-01T18:20:05.600236+00:00 app[worker.1]: raise self._exception
2020-10-01T18:20:05.600244+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/concurrent/futures/thread.py", line 56, in run
2020-10-01T18:20:05.600439+00:00 app[worker.1]: result = self.fn(*self.args, **self.kwargs)
2020-10-01T18:20:05.600443+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/jugaad_data/util.py", line 110, in wrapper
2020-10-01T18:20:05.600627+00:00 app[worker.1]: j = function(**kw)
2020-10-01T18:20:05.600632+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/jugaad_data/nse/__init__.py", line 75, in _stock
2020-10-01T18:20:05.600801+00:00 app[worker.1]: j = self.r.json()
2020-10-01T18:20:05.600805+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/requests/models.py", line 898, in json
2020-10-01T18:20:05.601212+00:00 app[worker.1]: return complexjson.loads(self.text, **kwargs)
2020-10-01T18:20:05.601237+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/json/__init__.py", line 354, in loads
2020-10-01T18:20:05.601530+00:00 app[worker.1]: return _default_decoder.decode(s)
2020-10-01T18:20:05.601534+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/json/decoder.py", line 339, in decode
2020-10-01T18:20:05.601754+00:00 app[worker.1]: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2020-10-01T18:20:05.601759+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/json/decoder.py", line 357, in raw_decode
2020-10-01T18:20:05.601972+00:00 app[worker.1]: raise JSONDecodeError("Expecting value", s, err.value) from None
2020-10-01T18:20:05.602034+00:00 app[worker.1]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-10-01T18:20:05.951067+00:00 heroku[worker.1]: Process exited with status 1

**Comment by sevakram** [comment]
Hi @Jainu-s ,

I'm suspecting one of the 3 reasons-
1. Bad NSE response
2. Threading error
3. Error due to caching

Let us try to debug step by step-

Please try this code first- 

```python
from jugaad_data import nse
from datetime import date
h = nse.NSEHistory()
# Fetch raw data from NSE's website
raw = h._stock("SBIN", date(2020,1,1), date(2020,1,31), "EQ")

# if above line works fine then we are receiving data as expected
# Try fetching for longer duration without threads
h.use_threads = False
raw = h.stock_raw("SBIN", date(2020,1,1), date(2020,6,30), "EQ")

# Try with threads
h.use_threads = True
raw = h.stock_raw("SBIN", date(2020,1,1), date(2020,6,30), "EQ")
```

Please let me know the output

**Comment by sevakram** [comment]
I'm also getting resource not found for some date ranges, which is why we are getting JSONDecodeError

'<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>Resource not found</title>\n</head>\n<body style="background-color: #e8e8e8;">\n  <div style="font-size: 32px; padding: 50px 25px; text-align: center;">\n    Resource not found\n  </div>\n</body>\n</html>\n'


Will have to dig deeper. Meanwhile, I suggest you can download bhavcopies and extract data from it.

**Comment by Jainu-s** [comment]
I have seen bhavcopy but it has 1800 + stocks. How to separate each stock detail and create a database of each stock. I have no Idea. Please help me regarding this. Thank you.

**Comment by sevakram** [comment]
Its working now, so I'm unable to test it, Only conclusion I can draw right now is -
1. We get JSONDecodeError when we get response like above
2. New NSE's website is not reliable enough

**Comment by Jainu-s** [comment]
Yes, Please upload new things like this. Thank you.
