### ISSUE TITLE
Jugaad_data stopped working

### ISSUE THREAD

**Issue by akrajarajan** [jugaad-py/jugaad-data#85]
### Issue description

I have been using the following program for getting data from NSE.  It was working well till two days ago but suddenly stopped working with the following error message.  Please help (- I have added the complete program as attachment. This program reads set of realtime price values once everytime the button is pressed)

[GetDataFromNSE.txt](https://github.com/user-attachments/files/17406392/GetDataFromNSE.txt)

### Example Code

```python
from jugaad_data.nse import NSELive
  
n = NSELive()
    
nifty_data = n.stock_quote("SBIN")
C = nifty_data['priceInfo']['lastPrice']
P = nifty_data['priceInfo']['pChange']

print(C,P)
```

### Error snippet

```python
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/AKR/NonScience/INVEST/AUTO/SubmittedJugaad_GITHUB.py", line 5, in <module>
    nifty_data = n.stock_quote("SBIN")
  File "C:\Program Files\Python311\Lib\site-packages\jugaad_data\util.py", line 172, in wrapper
    value = app_name(self, *args, **kwargs)
  File "C:\Program Files\Python311\Lib\site-packages\jugaad_data\nse\live.py", line 56, in stock_quote
    return self.get("stock_quote", data)
  File "C:\Program Files\Python311\Lib\site-packages\jugaad_data\nse\live.py", line 51, in get
    return r.json()
  File "C:\Program Files\Python311\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 2 (char 1)
```

**Comment by mriddyagrawal** [comment]
Is there any update on this bug? I also need help about it.

**Comment by AquaregiaAnubhav** [comment]
Something not similar. but a very basic fucntionality is not working. 
I ran the exact snippet given in the documentation of jugaad-data

```
# Download as pandas dataframe
df = index_df(symbol="NIFTY 50", from_date=date(2020,1,1), to_date=date(2020,1,30))

print(df.head())
```
and I get a wierd error as shown below:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-3-42eba021e7b6>](https://localhost:8080/#) in <cell line: 5>()
      3 
      4 # Download as pandas dataframe
----> 5 df = index_df(symbol="NIFTY 50", from_date=date(2020,1,1), to_date=date(2020,1,30))
      6 
      7 print(df.head())


[/usr/local/lib/python3.10/dist-packages/jugaad_data/nse/history.py](https://localhost:8080/#) in index_df(symbol, from_date, to_date)
    367     if not pd:
    368         raise ModuleNotFoundError("Please install pandas using \n pip install pandas")
--> 369     raw = index_raw(symbol, from_date, to_date)
    370     df = pd.DataFrame(raw)
    371     index_dtypes = {'OPEN': ut.np_float, 'HIGH': ut.np_float, 'LOW': ut.np_float, 'CLOSE': ut.np_float,

[/usr/local/lib/python3.10/dist-packages/jugaad_data/nse/history.py](https://localhost:8080/#) in index_raw(self, symbol, from_date, to_date)
    317         params = [(symbol, x[0], x[1]) for x in reversed(date_ranges)]
    318         chunks = ut.pool(self._index, params, max_workers=self.workers)
--> 319         return list(itertools.chain.from_iterable(chunks))
    320 
    321     @ut.cached(APP_NAME + '-index_pe')

[/usr/lib/python3.10/concurrent/futures/_base.py](https://localhost:8080/#) in result_iterator()
    619                     # Careful not to keep a reference to the popped future
    620                     if timeout is None:
--> 621                         yield _result_or_cancel(fs.pop())
    622                     else:
    623                         yield _result_or_cancel(fs.pop(), end_time - time.monotonic())

[/usr/lib/python3.10/concurrent/futures/_base.py](https://localhost:8080/#) in _result_or_cancel(***failed resolving arguments***)
    317     try:
    318         try:
--> 319             return fut.result(timeout)
    320         finally:
    321             fut.cancel()

[/usr/lib/python3.10/concurrent/futures/_base.py](https://localhost:8080/#) in result(self, timeout)
    449                     raise CancelledError()
    450                 elif self._state == FINISHED:
--> 451                     return self.__get_result()
    452 
    453                 self._condition.wait(timeout)

[/usr/lib/python3.10/concurrent/futures/_base.py](https://localhost:8080/#) in __get_result(self)
    401         if self._exception:
    402             try:
--> 403                 raise self._exception
    404             finally:
    405                 # Break a reference cycle with the exception in self._exception

[/usr/lib/python3.10/concurrent/futures/thread.py](https://localhost:8080/#) in run(self)
     56 
     57         try:
---> 58             result = self.fn(*self.args, **self.kwargs)
     59         except BaseException as exc:
     60             self.future.set_exception(exc)

[/usr/local/lib/python3.10/dist-packages/jugaad_data/util.py](https://localhost:8080/#) in wrapper(*args, **kw)
    107                 if not os.path.exists(cache_dir):
    108                     os.makedirs(cache_dir)
--> 109                 j = function(**kw)
    110                 with open(path, 'wb') as fp:
    111                     pickle.dump(j, fp)

[/usr/local/lib/python3.10/dist-packages/jugaad_data/nse/history.py](https://localhost:8080/#) in _index(self, symbol, from_date, to_date)
    311         }
    312         r = self._post_json("index_history", params=params)
--> 313         return json.loads(self.r.json()['d'])
    314 
    315     def index_raw(self, symbol, from_date, to_date):

KeyError: 'd'
```

**Comment by sevakram** [comment]
This issue has been resolved. Testing confirms that both historical and live data fetching are working correctly:
- Historical data fetching: ✓ Working
- Live stock data: ✓ Working
- Live index data: ✓ Working

All API endpoints are responding properly with valid JSON responses.
