### ISSUE TITLE
Full Bhavcopy Data for 2019 throwing exception

### ISSUE THREAD

**Issue by yash12392** [jugaad-py/jugaad-data#9]
Hi, I think better exception handling can be done in your code right now. For some reason, I cannot fetch any full_bhavcopy_save for 2019, and for prior years, I believe the data is not present anymore on https://archives.nseindia.com/products/content/sec_bhavdata_full_{ddmmyyyy}.csv

Are you planning to put any fix in there? Details of Exception below. 

Traceback (most recent call last):
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\requests\models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.nseindia.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bhavcopy_downloader.py", line 29, in <module>
    full_bhavcopy_save(dates, savepath)
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\jugaad_data\nse\archives.py", line 91, in full_bhavcopy_save
    text = self.full_bhavcopy_raw(dt)
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\jugaad_data\nse\archives.py", line 81, in full_bhavcopy_raw
    r = self.get("bhavcopy_full", yyyy=yyyy, mm=mm, dd=dd)
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\jugaad_data\nse\archives.py", line 52, in get
    self.r = self.s.get(url, timeout=self.timeout)
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\requests\sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\requests\sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\requests\sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\requests\sessions.py", line 697, in send
    r.content
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\requests\models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Users\Yash\anaconda3\envs\nse_env\lib\site-packages\requests\models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.nseindia.com', port=443): Read timed out.

**Comment by sevakram** [comment]
I dont think it has a fix (i mean to get the old data), but yes, we can do a better exception handling.

**Comment by yash12392** [comment]
Cool, you had like to check out a blog I covered for your library: https://tradewithpython.com/download-end-of-day-stock-prices-for-national-stock-exchange-of-india-using-python

Initially, I used the full_bhavcopy_save function but now that's broken, so I am amending all my articles in this series to show the data from bhavcopy_save

**Comment by sevakram** [comment]
Great job with the blog!!

Feel bad that you have to change all the codes, let me know if you find link for downloading full bhavcopies older than 2019
